;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-defun
        c-electric-colon
        c-electric-paren
        company-indent-or-complete-common
        crux-move-beginning-of-line
        delete-indentation
        easy-kill
        electric-newline-and-maybe-indent
        insert-register
        isearch-backward-regexp
        isearch-printing-char
        kill-region
        markdown-outdent-or-delete
        move-past-close-and-reindent
        paredit-backward
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-newline
        paredit-open-curly
        paredit-open-round
        paredit-open-square
        paredit-splice-sexp
        paredit-wrap-round
        smex
        sp-backward-sexp
        sp-backward-slurp-sexp
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-kill-region
        sp-splice-sexp
        sp-wrap-round
        transpose-sexps
        where-is
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        c-electric-pound
        c-electric-semi&comma
        yaml-electric-dash-and-dot
        ))
